spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/v1/board/**, /api/v1/boards
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/v1/member/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9001
jwt:
  expired:
    access-token: 300
    refresh-token: 3000
  secret: secret