spring:
  application:
    name: member-service
  data:
    redis:
      port: 6379
      host: localhost
eureka:
  instance:
    # DNS 대신 IP 주소 사용
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
jwt:
  expired:
    access-token: 300
    refresh-token: 3000
  secret: secret